# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsHistory',
            fields=[
                ('appointment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default=b'', max_length=100)),
                ('scheduled_time', models.DateTimeField()),
                ('arrive_time', models.DateTimeField(default=None, null=True)),
                ('waiting_duration', models.IntegerField(default=None, null=True)),
                ('session_start_time', models.DateTimeField(default=None, null=True)),
                ('session_duration', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
