# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('cell_phone', models.IntegerField()),
                ('body_weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('heart_rate_bpm', models.IntegerField()),
                ('body_temperature', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
