# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('body_weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('heart_rate_bpm', models.IntegerField()),
                ('body_temperature', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
