# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0003_auto_20190428_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbody',
            name='body_temperature',
            field=models.FloatField(),
        ),
    ]
